### PR TITLE
Fix for crash on API 28

### PR DESCRIPTION
**Pull request by 4face-studi0**
In some unclear circumstances, the app crashes with the exception described in the comment, while a `cut` operation is done with a single token set in the `TextView`

### CODE REVIEW

**Comment by mgod** [comment]
How are you getting to a `cut` operation? The view doesn't really support cut/copy/paste correctly right now.

**Comment by 4face-studi0** [comment]
With `setLongClickable` to `true`

**Comment by mgod** [comment]
Are you finding copy and paste work? Can you give me some more details about your use-case? I'm  guessing the actual underlying problem is that we should not be invalidating the view under some circumstances.

**Comment by Jacks0N23** [comment]
> I'm guessing the actual underlying problem is that we should not be invalidating the view under some circumstances.

Yes, i have the same crash after just trying to cut created token and crash somewhere near invalidate method

But i don't understand this pr fix, too many other changes, it's bad practice

**Pull request closed without merging**
