### PR TITLE
Use generics instead of unchecked casts for more type-safety

### LINKED ISSUE #46: Use generics instead of unchecked casts for more type-safety
I've changed the library (and the example app) to use generics to enforce type-safety at compile time. This keeps you from having to cast every Object that comes back from the view. The app code becomes much cleaner at the expense of generic use and some object casting in the library.

Let me know what you think, I could create a pull request if you like the changes.

https://github.com/octanner/TokenAutoComplete/commit/6b4685711a2134cee97998888ed2ecaf39494e67

### PR DESCRIPTION
**Pull request by austynmahoney**
I've changed the library (and the example app) to use generics to enforce type-safety at compile time. This keeps you from having to cast every Object that comes back from the view. The app code becomes much cleaner at the expense of generic use and some object casting in the library.

Closes #46

### CODE REVIEW

**Comment by Sirrah** [comment]
@mgod Are you still interested in merging this?

**Comment by mgod** [comment]
@Sirrah I've spent some time looking to make this change in the core app and keep running into issues with getting it working where I think I may just not know enough about Java to make it happy. I probably won't merge this particular pull request as the library has changed significantly since then, but this is something I would like to do.

**Comment by Sirrah** [comment]
Do you have a more current branch you've been working on or can you expand on the issues you ran into? I'll look into adding the generics myself as well.

**Comment by mgod** [comment]
Actually, looking over this PR again, I can't remember what I had trouble with. It seems like this should be pretty straightforward? At the time I was fussing with this, TokenImageSpan may have been a static class on my local copy which might have been the issue.

**Comment by Sirrah** [comment]
I just rebased this pr to the current master and gave it a more thorough look. It seems fine so far. I'll have to make some changes to my current project to test it out (currently I'm using 1.2.1 for the compatibility with older Android APIs). I'll come back to this tomorrow.

**Comment by Sirrah** [comment]
I've created a new pull request #120 updated for the current master. I did run into an issue with TokenImageSpan but was able to resolve it with an explicit cast.

**Comment by mgod** [comment]
Merged #120, which was an updated version of this with all of it's changes.

**Pull request closed without merging**
