### PR TITLE
Fix for autocompleting with cursor in the middle

### PR DESCRIPTION
**Pull request by dejarno**
Issue #173

### CODE REVIEW

**Comment by mgod** [comment]
This looks like it should work, but for better encapsulation, can you not add a new method to the class and instead use the existing ```findTokenEnd``` on the ```Tokenizer```? Should make it cleaner if someone is doing some odd token work.

**Comment by dejarno** [comment]
Implemented your feedback, makes more sense know. Let me know if something else needs to change!

**Comment by mgod** [comment]
Nice! Thanks for the changes.

**Comment by dejarno** [comment]
No problem! Any idea when this will be released?

**Pull request merged**
