### PR TITLE
Use generics instead of unchecked casts for more type-safety (updated)

### PR DESCRIPTION
**Pull request by Sirrah**
I've rebased the original pull request #47 to the current master and made some additional changes to get it working.

As mentioned in #47 there was an issue with the TokenImageSpan inner class. This was resolved with an explicit cast in 7de557b.

This was tested on the example app and on my own project.

### CODE REVIEW

**Comment by Sirrah** [comment]
Within `#getSerializableObjects()` the contents is currently copied to a `ArrayList<Serializable>`. This could be replaced by an explicit cast to `ArrayList<Serializable>`.

I was also looking into the changes necessary to support `Parcelable` objects. One IMO clean way to do this would be to extend the class hierarchy with the following:

```java
SerializableTokenCompleteTextView<T extends Serializable> extends TokenCompleteTextView<T>
ParcelableTokenCompleteTextView<T extends Parcelable> extends TokenCompleteTextView<T>
```
What are your thoughts about supporting Parcelable objects?

**Comment by mgod** [comment]
I'm not all that interested in supporting Parcelable objects. The library is pretty annoying to test (I don't have an automated test suite because a lot of the specific issues require doing things like running on a Samsung with stock keyboard within a specific device/os family), so I'd rather avoid adding more code paths to fuss with.

The main difference between Serializable and Parcelable as I understand it is performance. Parcelables look to process 2-10x faster than Serialazables, but in our case, we're talking about a few objects most of the time and only in orientation changes and restoring state, so I'm not sure the performance benefit is all that worth it. I'd much rather keep the simpler implementation with a smaller test burden. Are you seeing issues with the current implementation?

I will also note that I might be a bit biased here. My own use of this code uses non-Serializable, non-Parcelable objects which requires me to override the get/convert Serializable object methods to save keys and load from a database, so thats the path I have the most experience with. This is why I've kept the slower copy method in there with the checks so I get warnings if I screw it up.

If we can come up with a design that makes the get/convert methods more general and abstract in the base class and then make it magically easy to save/restore if you use the Serializable or Parcelable subclass, that does seem worth thinking through. Now is probably the time to fuss with this as I'll likely make the next update to 2.0 with the breaking change of adding this PR.

Thanks for the PR update and for keeping the original developers commits in here!

**Comment by Sirrah** [comment]
My reasoning was pretty much the same as yours with the difference being that the app I've inherited uses Parcelable objects instead of Serializable.

I don't care about the performance difference either but was slightly surprised that my Parcelable list wasn't preserved properly. Side note, due to the use of `system.out` instead of the logger I did not see the relevant warning message but I believe I saw a separate ticket for that.

I'm not sure how to make it magically easy unless we can work with the assumption that the entire array is either `ArrayList<? extends Parcelable>` or `ArrayList<? extends Serializable>`.
Testing and handling the individual elements separately would open up all sorts of edge cases like maintaining the proper order of the tokens.

Of course we can test whether the entire array is filled with Serializable or Parcelable objects and handle what would be the common case. But this would still introduce the third case where we do need to handle the objects individually. This would then open the user to possibly surprising behavior.
In my opinion the best way to avoid this and make the usage clear to the user is to use the type system to communicate these restrictions.

For now it was easy enough to handle saving the instance state of the object array myself in the class implementing TokenCompleteTextView.

Thank you for the library! It really helped me with my current project.

**Comment by mgod** [comment]
@Sirrah I would be open to requiring all the objects to be either all Parcelable or all Serializable, though I'm not sure which way I should point new users in the docs. Let's get this merged first, though.

**Pull request merged**
