### PR TITLE
New option completeOnFocusLost

### PR DESCRIPTION
**Pull request by GAumala**
When set to `false`, this option turns off completing unfinished tokens when the view loses focus. 

The current behavior is that if the user writes something like "gabriel" and the view loses focus, it will automatically be completed with something like "gabriel@gmail.com", Which may not be ok for some users.

When the option is set to `false`, if the user writes something like "gabriel" and the view loses focus, the unfinished token's text remains unchanged, and when the focus returns to the view, autocompletion resumes normailly.

As a plus, if the unfinished token is a valid email adress, then the token is completed when the view loses focus, regardless of the value of `completeOnFocusLost`. Validation is performed using [a regular expression from the Android Plataform](https://developer.android.com/reference/android/util/Patterns.html#EMAIL_ADDRESS).

### CODE REVIEW

**Comment by mgod** [comment]
I'm open to considering adding the first commit to the core project, but lots of people use this for things that aren't email addresses, so I'm not open to adding an email-specific behavioral override. Do you need that part of the behavior or maybe there is a way to make it generic without overcomplicating the feature?

I'm still pretty skeptical of this behavior in general, and it adds another tricky test path to the project. Can you give me some idea of what your use case is?

**Comment by GAumala** [comment]
I'm sorry, I incorrectly assumed that this project was strictly for email addresses. My bad. Second commit will be removed.

I use TokenAutoComplete on a email client, and I only want to have tokens with valid email adresses. Ideally I'd like to be able to style the unfinished token when the view loses focus so that the user can instantly receive feedback about an invalid email address, but I'm not sure yet about how to accomplish it. Leaving the unfinished token as is instead of performing a best guess is a good first step. 

I think a better solution would be a "strict mode" where tokens are only allowed if they exist in the provided object list or are validated by some arbitrary function also provided by the user.

**Comment by mgod** [comment]
Ah, for that I'd recommend leaving in the behavior that tokenizes input, then use the ```onTokenAdded``` callback to look at what got added and either remove it and show a view to fix the input or just ignore it.

**Comment by mgod** [comment]
You can also return ```null``` from ```defaultObject``` which will silently discard the input when you tokenize it and it's not selected from the list.

**Comment by GAumala** [comment]
returning a "invalid object" from `defaultObject` worked like charm! I can also return a diferent view for this kind objects to display feedback about invalid addresses. Thanks a lot for the help!

**Pull request closed without merging**
