### PR TITLE
Fixed https://github.com/splitwise/TokenAutoComplete/issues/85 and a few other issues

### PR DESCRIPTION
**Pull request by premnirmal**
- Fixed https://github.com/splitwise/TokenAutoComplete/issues/85

- Fixed crash when holding delete key

- Fixed empty tag added when you hit ',' with no prefixing text

- updated gradle version

### CODE REVIEW

**Comment by mgod** [comment]
Hi @premnirmal – sorry to be so slow to respond to this. I didn't merge quickly this because there was a fair amount going on in the code and it was difficult to figure out which changes corresponded to which fixes.

I think the changes made for 1.3.0 and 1.3.1 fixed everything here except the crash on holding the delete key. Are c7bd311 and 24e7c38 the only commits for the backspace issue? I'd love to pull that fix into the main repository.

**Comment by premnirmal** [comment]
Hi @mgod , that's right those are the only two commits for the backspace issue

**Comment by mgod** [comment]
Just to check – it looks like the try/catch on 713 is to prevent index out of bounds errors? also in the ```extractText``` override? I'd really prefer not to have blanket catches like that. Do you remember what steps you needed to do to get those crashes?

**Comment by premnirmal** [comment]
@mgod I eventually removed the try catch (if you see the tip of my master branch there's no try catch).
But I was seeing the exception being thrown when holding delete and attempting to remove all tokens, or adding/removing multiple tokens by calling addObject/removeObject repeatedly.

**Pull request closed without merging**
