### PR TITLE
don't unconditionally use toString for span reconstruction after collapse

### PR DESCRIPTION
**Pull request by Valodim**
fix for #195 (and #202)

### CODE REVIEW

**Comment by mgod** [comment]
Thanks!

**Comment by Valodim** [comment]
I would appreciate a quick release so I can include this fix in OpenKeychain and K-9 without adding the lib from source :+1:

**Comment by mgod** [comment]
2.0.7 should be available within the next couple of hours.

**Comment by Valodim** [comment]
awesome, thanks

**Comment by sperls** [comment]
will this be included in the gradle library anytime soon?

**Comment by mgod** [comment]
2.0.7 already includes this fix.

**Comment by sperls** [comment]
hmm, this is still happening for me. I posted another issue, and I've only seen this to happen after that, maybe they're related? Ticket #218 where tokens duplicate after list collapses and re-expands. Then when I try to delete one of the duplicate tokens, it seems to use the toString deletion style.

**Comment by mgod** [comment]
@sperls there's some default handling in the AutoCompleteTextView that forces text recovery in cases where the token is the most recently completed.

**Pull request merged**
